/*tell which database you will use*/
USE HR;

ALTER TABLE `location`
ADD CONSTRAINT `fk_location_1`
  FOREIGN KEY (`COUNTRY_ID`)
  REFERENCES `country` (`COUNTRY_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

ALTER TABLE `department`
ADD CONSTRAINT `fk_department_1`
  FOREIGN KEY (`LOCATION_ID`)
  REFERENCES `location` (`LOCATION_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

ALTER TABLE `job_history`
ADD CONSTRAINT `fk_job_history_employee1`
  FOREIGN KEY (`EMPLOYEE_ID`)
  REFERENCES `employee` (`EMPLOYEE_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

ALTER TABLE `employee`
ADD CONSTRAINT `fk_employee_2`
  FOREIGN KEY (`DEPARTMENT_ID`)
  REFERENCES `department` (`DEPARTMENT_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;
  
ALTER TABLE `HR`.`employee`
ADD CONSTRAINT `fk_employee_3`
  FOREIGN KEY (`JOB_ID`)
  REFERENCES `HR`.`job` (`JOB_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;  

ALTER TABLE `job_history`
ADD CONSTRAINT `fk_job_history_2`
  FOREIGN KEY (`JOB_ID`)
  REFERENCES `job` (`JOB_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;
