-- What is the total revenue generated by each customer over the past year?

SELECT 
    o.CustomerID, 
    SUM(o.TotalAmount) AS TotalRevenue
FROM 
    Orders o
WHERE 
    o.OrderDate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY 
    o.CustomerID
ORDER BY 
    TotalRevenue DESC;

-- What is the average order value (AOV) for each product category in the last quarter?

SELECT 
    p.CategoryID,
    AVG(od.Subtotal) AS AverageOrderValue
FROM 
    OrderDetails od
JOIN 
    Products p ON od.ProductID = p.ProductID
JOIN 
    Orders o ON od.OrderID = o.OrderID
WHERE 
    o.OrderDate BETWEEN '2023-10-01' AND '2023-12-31'
GROUP BY 
    p.CategoryID
ORDER BY 
    AverageOrderValue DESC;

-- How much stock of each product is currently available, and which product is low in stock?

SELECT 
    p.ProductID, 
    p.ProductName, 
    p.StockQuantity
FROM 
    Products p
WHERE 
    p.StockQuantity <= 20
ORDER BY 
    p.StockQuantity ASC;


--  What are the top 5 best-selling products for the last month, in terms of quantity sold?

SELECT 
    p.ProductName, 
    SUM(od.Quantity) AS TotalQuantitySold
FROM 
    OrderDetails od
JOIN 
    Products p ON od.ProductID = p.ProductID
JOIN 
    Orders o ON od.OrderID = o.OrderID
WHERE 
    o.OrderDate BETWEEN '2023-11-01' AND '2023-11-30'
GROUP BY 
    p.ProductName
ORDER BY 
    TotalQuantitySold DESC
LIMIT 5;

-- What is the total revenue generated by each product in the last six months?

SELECT 
    p.ProductName,
    SUM(od.Subtotal) AS TotalRevenue
FROM 
    OrderDetails od
JOIN 
    Products p ON od.ProductID = p.ProductID
JOIN 
    Orders o ON od.OrderID = o.OrderID
WHERE 
    o.OrderDate BETWEEN '2023-06-01' AND '2023-11-30'
GROUP BY 
    p.ProductName
ORDER BY 
    TotalRevenue DESC;

